services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: canto_martinez_carlosenrique
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    secrets:
      - mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
